#!/bin/sh



echo "Ethereum Wallet Transfer"
echo "From"  $1
echo "To" $2
echo "Ammount" $3 


echo "Your Wallet is:"
./geth --testnet --fast -exec "eth.accounts" attach 


echo "Transaction"

#./geth --testnet --fast -exec "eth.sendTransaction({from:'$1', to: '$2', value: '$3'})" attach

 

*************************************************************************************************************************************
./geth --testnet --fast --ipcpath /home/stud/.ethereum//geth.ipc console


>personal.unlockAccount(sender, "passwd")
> eth.sendTransaction({from: sender, to: reciever, value: 24})
> eth.getBalance(sender)
> var amount = web3.toWei(0.01,INFO [06-05|19:26:10] Imported new chain segment               blocks=1 txs=1  mgas=0.021 elapsed=6.624ms   mgasps=3.170  number=1062216 hash=e893ae…f95cbb
> var amount = web3.toWei(2, "ether")
undefined
> amount
"2000000000000000000"
> var amount = web3.toWei(0.001, "ether")
undefined
>eth.sendTransaction({from: sender, to: reciever, value: amount})

> eth.getBalance(sender)
